apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      environment: production
  template:
    metadata:
      name: nginx-pod
      labels:
        environment: production
    spec:
      containers:
        - name: nginx
          image: nginx:latest
